name: Java CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-image:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: studybuddy
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U testuser -d studybuddy"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Verify with Maven (tests included)
        run: |
          export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/studybuddy
          export SPRING_DATASOURCE_USERNAME=testuser
          export SPRING_DATASOURCE_PASSWORD=testpass
          ./mvnw -B verify

      - name: Build Docker image
        run: docker build -t studybuddy:latest .
